### ISSUE TITLE
Win32 version

### ISSUE THREAD

**Issue by username1565** [Karasiq/nanoboard#4]
I have the following error when I running exe-file on `Windows XP`:
>%1 эх  ты хЄё  яЁшыюцхэшхь Win32.

[Универсальный декодер](https://2cyr.com/decode/?lang=ru) говорит это:
>%1 не вл етс приложением Win32.

Дальше - пишу на английском, но можно и по русски.
________________________________________
Can you recompile this as win32.exe? gcc compilator have separate option for this programs `-m32`.
Also, you can use `-O3` option to optimize compilation if you using gcc compilator.
____________________
P.S. I did try to run this on Windows 8.1 (x64),
and setup go to installation folder "C:\Program Files (x86)\Nanoboard\"
That means this x86-64 not x32 program...

Also, I see some bugs. I cann't specify the port in the settings.
And I cann't using `#` to save some comments.
```
#like this comment
https://127.0.0.1:8080/my_folder_for_png_files/dynamic_filelist.html
```

Can you fix this all troubles?

Best regards.

**Comment by username1565** [comment]
Nanoposts from karasiq-nanoboard v1.3.2, where some file included,
this post cann't be loaded in NanoBoard client: 3.0
from PNG, which created inside karasiq-nanoboard.

But in Nanoboard client 3.0 I see this thread with pure text: 
http://127.0.0.1:7346/pages/index.html#threada8fc5d7e8a19b9b4aa015c584cc9135a

Also, not all posts loaded, I don't see categories which available in old nanoboard 3.0,
and nanoboard client 3.0 cann't read nanoposts from karasiq PNG's...
_____
Fix this troubles to save backward compatibility.

**Comment by Karasiq** [comment]
> %1 эх ты хЄё яЁшыюцхэшхь Win32.

It's a Launch4j issue, as a workaround you can use an "universal" zip version.

>this post cann't be loaded in NanoBoard client: 3.0

You should **verify** the post to receive it with 3.0

**Comment by Karasiq** [comment]
I tested just now, both text-only and picture posts was received in 3.0 without problems.

**Comment by username1565** [comment]
@Karasiq, спасибо за ваш ответ.
>as a workaround you can use an "universal" zip version.

В zip-версии я вижу три файла:
1. "/bin/nanoboard-server" - двоичный файл.
2. "/bin/nanoboard-server.bat" - файл для запуска его.
3. "/lib/nanoboard-server.jar" - какой-то jar-файл...

Для запуска JAR-файла `nanoboard-server.jar` , я создал следующий bat-file: `start_JAR.bat`
И прописал туда вот этот код: `java -jar nanoboard-server.jar`
Пытаюсь запустить JAR-файл...
```
Полный_путь_к_папке_lib>start_JAR.bat
PATHWAY\lib>java -jar nanoboard-server.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/karasiq/n
anoboard/server/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClassInternal(Unknown Source)
Could not find the main class: com.karasiq.nanoboard.server.Main. Program will e
xit.
```

Пытаюсь запустить уже существующим файлом `nanoboard-server.bat`.
Та же ошибка:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/karasiq/n
anoboard/server/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClassInternal(Unknown Source)
Could not find the main class: com.karasiq.nanoboard.server.Main.  Program will
exit.
```

Поэтому, zip-версия - не работает на Windows XP (x32), хотя Java установлен.
Я вижу, какую-то ссылку там, и вижу что программа хочет
какие-то сторонние библиотеки.
Это значит, что код неполный, и прога не портабельна.

А вот в Windows 8.1 (x64) zip-версия работает по обоим bat-файлам.

>It's a Launch4j issue

И как исправить это?
После установки софтины, инсталлятором, в папке "/Program Files/Nanoboard"
я вижу, что файл `nanoboard.exe` является `SFX-ZIP`-архивом,
и может быть открыт, как архив - программой WinRAR.
Там, внутри, какие-то файлы, с исходным кодом на языке `Scala`.
Я должен что-то изменить там что-ли, чтобы починить этот ваш неведомый `Launch4j`?

>You should verify the post to receive it with 3.0

Хм, а как **проверить пост**?
Просто загрузить последние посты?
Или надо обязательно добавлять пост - в очередь,
чтобы он застеганографировался в контейнере?
Я вижу, в [Readme.md](https://github.com/Karasiq/nanoboard/blob/master/README.MD) у вас, где Features,
>Option to verify existing posts

Это отдельный аргумент в коммандной строке что-ли?

>I tested just now, both text-only and picture posts was received in 3.0 without problems.

Текст и картинки - значит работают...

Кстати, а вы пробовали запостить другой файл, какой-нибудь, txt, например?
Я знаю, что версии 3.0 можно постить в виде base64,
только картинки (со сжатием) и zip-архивы (без сжатия). А у вас - любой файл.
Как там, в клиенте 3.0 отображаются другие файлы - я пока без понятия.
Скорее всего будет видно поток бейса.

**Comment by Karasiq** [comment]
>Unsupported major.minor version 52.0

У вас установлена старая JRE
См. https://www.oracle.com/technetwork/java/javase/downloads/index.html#JDK8

>Я должен что-то изменить там что-ли, чтобы починить этот ваш неведомый Launch4j?

Это на моей стороне надо пересобирать. Launch4j это просто враппер явы в исполняемый файл.
Сама по себе программа полностью кроссплатформенная и работает в т.ч. под линуксом.

> Хм, а как проверить пост?

Снизу поста есть кнопка Verify (подтвердить), она верифицирует пост с помощью POW и капчи.

> Как там, клиенте 3.0 отображаются другие файлы - я пока без понятия.

Там поддерживается только base64 ссылка, в моём клиенте сделан кастомный BB-код для файлов.

**Comment by username1565** [comment]
> У вас установлена старая JRE

```
>java -version
java version "1.6.0_12"
Java(TM) SE Runtime Environment (build 1.6.0_12-b04)
Java HotSpot(TM) Client VM (build 11.2-b01, mixed mode)
```

Cкачал я, по вашей ссылке `jre-8u191-windows-i586.exe` и `jre-8u192-windows-i586.exe`
Так они, оба, вообще на XP - не запускаются.
Похожи на установочные файлы. В имени файла вижу i586, у меня же - i386.
Как чинить - не знаю.

> Launch4j это просто враппер явы в исполняемый файл.

Я в этом вообще не разбираюсь.

> Это на моей стороне надо пересобирать.

Ну, если можно починить чё-то, вам лучше знать.
Я вижу ссылку какую-то там, не в тему сунутую, возможно поэтому баги и лезут.
Там iplogger, или что?

> Снизу поста есть кнопка Verify (подтвердить), она верифицирует пост
    с помощью POW и капчи.

Нашёл, по русскому названию - работает. Благодарю.

> Там поддерживается только base64 ссылка,
    в моём клиенте сделан кастомный BB-код для файлов.

Вот и славненько, но я не тестил, пока. Занят немного...

В общем-то, прикольная софтина,
но она должна бы быть реально кроссплатформенной
(и x86, и x86-64, и x64), а не только (x86-64),
и к тому же портабельной, впоть до годной JRE, внутри.
И конечно же - это ИМХО.

**Comment by Karasiq** [comment]
>Так они, оба, вообще на XP - не запускаются.

Ну это к Oracle.

>Я вижу ссылку какую-то там, не в тему сунутую, возможно поэтому баги и лезут.

Где?

>В общем-то, прикольная софтина,
но она должна бы быть реально кроссплатформенной
(и x86, и x86-64, и x64), а не только (x86-64),
и к тому же портабельной, впоть до годной JRE, внутри.
И конечно же - это ИМХО.

Она кроссплатформенна настолько же, насколько и машина явы.
Launch4j встраивает JRE, но я не нашёл там опции для 32 бит.

**Comment by username1565** [comment]
>Я вижу ссылку какую-то там, не в тему сунутую, возможно поэтому баги и лезут.
Где?

А вот она (ещё и не полная):
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/karasiq/n
anoboard/server/Main : Unsupported major.minor version 52.0
```
>com/karasiq/nanoboard/server/Main

`Launch4j встраивает JRE, но я не нашёл там опции для 32 бит.`
Ладно, пофиг на x32, раз нет опции, а на x64 системе нборда и так нормально работает.
Вопрос закрываю...

**Comment by Karasiq** [comment]
>com/karasiq/nanoboard/server/Main

Это название класса, если что

**Comment by username1565** [comment]
Гляньте вот тут инфо по наноборде: https://github.com/nanoboard/nanoboard/issues/1
Можно в TOR'e захостить её через HFS-сервера.

**Comment by Karasiq** [comment]
> Гляньте вот тут инфо по наноборде: [nanoboard/nanoboard#1](https://github.com/nanoboard/nanoboard/issues/1)
> Можно в TOR'e захостить её через HFS-сервера.

Захостить можно и без извращений в виде HFS с картинками, а просто сделав приложение-ретранслятор. Но тогда борда будет зависеть от держателей серверов и требовать постоянного онлайна.

**Comment by username1565** [comment]
Зато вот [здесь](https://github.com/nanoboard/nanoboard/issues/4#issuecomment-452215775)
я перекомпилил клиент 3.0 добавив туда порт.
И теперь возможно на любой порт повесить HFS-сервер с картинками,
прописав его как тред с контейнерами, в настройках.
А у вас даже порт нельзя указать (символ `:` не допускается)...

А так-то, можно было бы просто списки магнет-ссылок ретранслировать,
они мало места занимают,
а приложение-ретранслятор сделать децентрализированным,
в виде пиринговой сети, состоящей из нод.
А сами же картинки - слать через торренты,
также как распространяется **[Wikileaks insurance torrents](https://en.wikipedia.org/wiki/List_of_material_published_by_WikiLeaks)**.
![wikileaksscreenshot 1](https://user-images.githubusercontent.com/39200328/51364009-23adc580-1ae3-11e9-8976-f2be30d2914e.png)
И чтобы всё это поднять, тут столько всего надо бы накодить...
Но есть исходники децентрализированнейшего [TOX'a](https://tox.chat/download.html) и torrent'а,
остаётся только одно к другому пришпандорить, и завести всё это дело. =)

**Comment by username1565** [comment]
И ещё, если хотите, можете - жипег стеганографию себе в борду пришпандорить!
Вот тут гляньте исходник [js-jpeg-steg](https://username1565.github.io/js-jpeg-steg).
